print ('*'*56)
print ('*'*3+' '*50+'*'*3)
print ('*'*3+' '*12+'Bienvenido al Tragamonedas'+' '*12+'*'*3)
print ('*'*3+' '*50+'*'*3)
print ('*'*56)
print ('')
print ('En este juego de azar apuestas al giro de tres rodillos,')
print ('los que toman valores de 1 a 9, o el comodin "*".')
print ('')
print ('Para comenzar, ingresa dinero a tu "bolsillo" (tiene que')
print ('ser al menos $500), desde este pozo realizaras apuestas:')
print ('la apuesta maxima es de $500 y la minima de $10. La fle-')
print ('cha que aparecera al lado izquierdo señaliza la linea de')
print ('pago de las combinaciones, que son:')
print ('')
print ('Tres comodines: 100x')
print ('Tres numeros iguales: 50x')
print ('Dos comodines y un numero: 25x')
print ('Dos numeros iguales y un comodin: 10x')
print ('Dos comodines: 5x')
print ('Dos numeros iguales: 3x')
print ('Un comodin: 1x')
